### ISSUE TITLE
generate .h5 file

### ISSUE THREAD

**Issue by YunlianMoon** [tailongnguyen/RL-target-driven-navigation-ai2thor#1]
Hi,
form the website (http://ai2thor.allenai.org/tutorials/installation)，do you know how to generate .h5 file, such as, bathroom_01.h5, FloorPlan1.h5.

**Comment by YunlianMoon** [comment]
I want to generate bathroom_05.h5,  because I want to realize one github code (https://github.com/yushu-liu/icra2017-visual-navigation)

**Comment by tailongnguyen** [comment]
@YunlianMoon  please read the code in file tf_a2c/dumping.py

**Comment by YunlianMoon** [comment]
@tailongnguyen can it generate scene dumps like (https://github.com/yushu-liu/icra2017-visual-navigation)?

**Comment by tailongnguyen** [comment]
@YunlianMoon yes, but I use different names for datasets. Please read the code. Thanks
